name: pos
description: Kirana POS Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔍 Scanner & API
  mobile_scanner: ^5.0.0
  http: ^0.13.6

  # 🗄 Local Storage
  sqflite: ^2.3.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # 🔥 Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # 🔐 Social Login
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 🚀 App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  # ✅ Main Assets Folder
  assets:
    - assets/icon.png
    - assets/images/